feat(consumer): add an option for consumers to conditionally ack the …
first-digital-finance/pyrmq pull request #34
Opened 2021-01-19 10:27 UTC by alecgerona

…received messages

2021-01-19 11:26 UTC, sibayanjasper requested changes

2021-01-19 11:26 UTC, sibayanjasper commented on pyrmq/consumer.py
> +        :keyword auto_ack: Flag whether to ack or nack the consumed message regardless of its outcome. Default: ``True``
`Flag whether to ack or nack` but we never nack.

2021-01-19 11:28 UTC, sibayanjasper commented
@alecgerona why is the PR description like that?

2021-01-19 11:31 UTC, sibayanjasper commented
> @alecgerona why is the PR description like that?

oh it's from the commit message
maybe avoid using long commit message on the first line
use something like a short commit title on the first line and then short/long explanation/description from the 3rd line onwards

2021-01-19 11:32 UTC, sibayanjasper commented
> > @alecgerona why is the PR description like that?
> 
> oh it's from the commit message
> maybe avoid using long commit message on the first line
> use something like a short commit title on the first line and then short/long explanation/description from the 3rd line onwards

if you're using git commit in terminal and use vim (or any editor) for the message, it will tell you that the first line is too long

2021-01-21 02:59 UTC, alecgerona commented
> > @alecgerona why is the PR description like that?
> 
> oh it's from the commit message
> maybe avoid using long commit message on the first line
> use something like a short commit title on the first line and then short/long explanation/description from the 3rd line onwards
> 
> if you're using git commit in terminal and use vim (or any editor) for the message, it will tell you that the first line is too long

Yeah I'm using commitizen. I'll fix this commit. There's an option for an extended commit description there. Just wasn't sure that it would display it like this tho.

2021-02-01 03:38 UTC, sibayanjasper approved these changes

2021-02-01 03:40 UTC, merged